### ISSUE TITLE
Aliasing does not work like the documentation says.

### ISSUE THREAD

**Issue by Starz0r** [gabdube/native-windows-gui#154]
The [documentation](https://github.com/gabdube/native-windows-gui#rust-2018-aliasing) would have you believe that this works:

- Cargo.toml
```toml
[dependencies]
nwg = {version = "1.0.7", package = "native-windows-gui", features = ["all"]}
native-windows-derive = "1.0.2"
```

- main.rs 
```rs
extern crate native_windows_derive as nwd;

use nwd::NwgUi;
use nwg::NativeUi;

#[derive(Default, NwgUi)]
pub struct App {
    #[nwg_control(size: (300, 300), position: (0, 0), title: "foobar", flags: "WINDOW|VISIBLE")]
    window: nwg::Window,
}

fn main () {}
```

However, it is simply untrue and does not work. You must declare the dependencies and crates as such:

- Cargo.toml 
```toml
native-windows-gui = {version = "1.0.7", features = ["all"]}
native-windows-derive = "1.0.2"
```

- main.rs
```rs
extern crate native_windows_gui as nwg;
extern crate native_windows_derive as nwd;
```

If you did intend for this to work somehow, I ask that you either revise the documentation, or remove it, as it is completely misleading.
